name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Triggers when you push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/taskflow-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-app:latest

##🔄 What this Workflow Does:
#Runs whenever you push to the main branch.

#Builds your Spring Boot app using Maven.

#Logs into Docker Hub with your saved secrets.

#Builds the Docker image using your Dockerfile.

#Pushes it to your Docker Hub repo as latest.

